#! /bin/sh

# Depends:
#  python,
#  python-mock,
#  python3,
#  python3 (>= 3.3) | python3-mock

if ! [ -r preload/libclickpreload.so ]; then
    echo "W: preload bits not built; will skip some tests" >&2
fi

if [ -z "$*" ]; then
	set -- discover clickpackage.tests
fi

if which python >/dev/null 2>&1; then
	python -m unittest "$@"
fi
if which python3 >/dev/null 2>&1; then
	python3 -m unittest "$@"
fi
